import { Link } from 'react-router-dom'
import { ArrowRight, Headphones, RefreshCw, Smartphone, Store, Wifi, Briefcase, TrendingUp, Wrench, CheckCircle2 } from 'lucide-react'
import InfoCard from '../components/InfoCard'
import SectionHeading from '../components/SectionHeading'
const companies=[['telcel','bg-[#245eae]'],['AT&T','bg-[#238cc5]'],['Movistar','bg-[#4a9d4f]'],['Unefon','bg-[#ffd53c] text-slate-900'],['bait','bg-black'],['Más opciones','bg-white/10 border border-white/20']]
export default function Home(){return <div className="page"><section className="relative min-h-[510px] overflow-hidden bg-[#082a47] text-white"><img className="absolute inset-0 h-full w-full object-cover opacity-55" src="https://images.unsplash.com/photo-1512428559087-560fa5ceab42?auto=format&fit=crop&w=1800&q=85"/><div className="absolute inset-0 bg-gradient-to-r from-[#061d32] via-[#082a47]/88 to-[#082a47]/20"/><div className="absolute -left-28 bottom-[-140px] h-[430px] w-[600px] rounded-full border-[70px] border-cyan-400/10"/><div className="shell relative z-10 flex min-h-[510px] items-center py-16"><div className="max-w-2xl"><p className="eyebrow text-cyan-300">TARJETAS SIM · PORTABILIDAD · CONECTIVIDAD</p><h1 className="mt-3 text-5xl font-black leading-[1.02] md:text-7xl">Conectamos a México,<br/><span className="text-[#52d0db]">tú eliges la compañía</span></h1><p className="mt-6 max-w-xl text-lg leading-8 text-slate-200">Evolución Telefónica reúne opciones de las principales compañías del país para brindarte libertad de elegir la red que mejor se adapte a tus necesidades.</p><div className="mt-8 flex flex-wrap gap-4"><Link to="/soluciones" className="btn-primary">Conoce nuestras soluciones <ArrowRight size={16}/></Link><Link to="/puntos-de-venta" className="btn-secondary border-white/50 bg-white/5 text-white">Quiero ser Punto de Venta</Link></div></div></div></section>
<section className="bg-white"><div className="shell grid gap-5 py-7 md:grid-cols-[.85fr_1.15fr]"><div className="flex items-center"><p className="text-lg font-black text-[#17324a]">Encuentra opciones de las principales compañías en un solo lugar.</p></div><div className="grid grid-cols-3 gap-3 md:grid-cols-6">{companies.map(([n,c])=><div key={n} className={`flex min-h-[62px] items-center justify-center rounded-xl px-3 text-center text-sm font-black ${c}`}>{n}</div>)}</div></div></section>
<section className="section"><div className="shell grid items-center gap-10 lg:grid-cols-[.8fr_1.2fr]"><div><SectionHeading eyebrow="¿QUIÉNES SOMOS?" title="Más opciones para mantenerte conectado." text="Nuestro objetivo es brindar libertad de elección en un solo lugar y facilitar el acceso a la conectividad móvil."/><Link to="/quienes-somos" className="btn-secondary mt-7">Conoce más sobre nosotros <ArrowRight size={16}/></Link></div><div className="grid gap-5 md:grid-cols-3"><InfoCard icon={Smartphone} title="Variedad de compañías" text="Diferentes opciones de conectividad en un solo lugar."/><InfoCard icon={RefreshCw} title="Portabilidad" text="Cambia de compañía sin perder tu número actual."/><InfoCard icon={Headphones} title="Asesoría" text="Información sobre planes, cobertura, beneficios y promociones."/></div></div></section>
<section className="dark-band text-white"><div className="shell section"><SectionHeading light eyebrow="NUESTRAS SOLUCIONES" title="¿Qué puedes hacer con nosotros?" text="Encuentra alternativas para adquirir una nueva SIM, conocer opciones de portabilidad y recibir orientación."/><div className="mt-10 grid gap-5 md:grid-cols-2 lg:grid-cols-4">{[[Smartphone,'Adquiere una nueva SIM','Encuentra opciones de diferentes compañías.'],[RefreshCw,'Cambia de compañía','Explora alternativas para conservar tu número.'],[Wifi,'Encuentra una opción para ti','Conoce alternativas según tus necesidades.'],[Headphones,'Recibe asesoría','Información sobre planes, cobertura y beneficios.']].map(([I,t,d])=><InfoCard key={t} icon={I} title={t} text={d} dark/>)}</div></div></section>
<section className="section"><div className="shell"><SectionHeading eyebrow="PUNTOS DE VENTA Y SOCIOS COMERCIALES" title="Haz crecer tu negocio con Evolución Telefónica." text="Integra soluciones de conectividad a tu negocio y ofrece a tus clientes diferentes opciones en un solo lugar."/><div className="mt-10 grid gap-5 md:grid-cols-2 lg:grid-cols-4">{[[Store,'Amplía tu catálogo','Ofrece nuevas opciones de conectividad.'],[Briefcase,'Más opciones','Permite que tus clientes puedan elegir.'],[Wrench,'Herramientas y apoyo','Accede a recursos para comenzar a operar.'],[TrendingUp,'Nuevas oportunidades','Integra soluciones a tu Punto de Venta.']].map(([I,t,d])=><InfoCard key={t} icon={I} title={t} text={d}/>)}</div><Link to="/puntos-de-venta" className="btn-primary mt-8">Quiero ser Punto de Venta <ArrowRight size={16}/></Link></div></section>
<section className="dark-band"><div className="shell grid gap-8 py-10 md:grid-cols-[1fr_auto]"><div><p className="eyebrow text-cyan-300">NUESTRA DIFERENCIA</p><h2 className="mt-2 text-3xl font-black text-white">Más opciones. Más libertad. Más conectividad.</h2><p className="mt-3 max-w-2xl text-sm leading-6 text-slate-300">Acercamos alternativas de telefonía móvil y conectividad para facilitar una mejor elección.</p></div><div className="flex items-center"><Link to="/contacto" className="btn-primary">Hablemos <ArrowRight size={16}/></Link></div></div></section></div>}
