import { Building2, HeartHandshake, RefreshCw, ShieldCheck, Smartphone, Wifi, ArrowRight, RadioTower } from 'lucide-react'
import { Link } from 'react-router-dom'
import VisualHero from '../components/VisualHero'
import InfoCard from '../components/InfoCard'
import SectionHeading from '../components/SectionHeading'
export default function About(){return <div className="page"><VisualHero eyebrow="SOMOS MÁS QUE TELEFONÍA, SOMOS CONECTIVIDAD" title={<>¿Quiénes somos?<br/><span className="text-[#52d0db]">Evolución Telefónica, conectando opciones.</span></>} text="Somos una empresa mexicana dedicada a la venta de tarjetas SIM de todas las compañías telefónicas del país. Nuestro objetivo principal es brindar libertad de elección, todo en un solo lugar." image="https://images.unsplash.com/photo-1512941937669-90a1b58e7e9c?auto=format&fit=crop&w=1800&q=85" primary="Conoce nuestras soluciones" primaryLink="/soluciones" dark/>
<section className="section"><div className="shell grid gap-5 md:grid-cols-3">{[[Smartphone,'Variedad de compañías','Contamos con opciones de las principales compañías telefónicas del país.'],[RefreshCw,'Portabilidad','Opciones para cambiar de compañía conservando tu número.'],[HeartHandshake,'Asesoría personalizada','Información sobre planes, cobertura, beneficios y promociones.']].map(([I,t,d])=><InfoCard key={t} icon={I} title={t} text={d}/>)}</div></section>
<section className="dark-band text-white"><div className="shell grid items-center gap-10 py-16 lg:grid-cols-[1fr_.9fr]"><div><SectionHeading light eyebrow="NUESTRA MISIÓN" title={<>Facilitar el acceso<br/><span className="text-[#52d0db]">a la conectividad móvil.</span></>} text="Promovemos la competencia en el sector de las telecomunicaciones y buscamos garantizar una mejor experiencia para cada usuario, con opciones flexibles, seguras y accesibles."/></div><div className="grid gap-4 sm:grid-cols-2">{[[Wifi,'Conectividad'],[Building2,'Libertad de elección'],[ShieldCheck,'Confianza'],[HeartHandshake,'Siempre contigo']].map(([I,t])=><div key={t} className="rounded-2xl border border-white/10 bg-white/10 p-6"><I className="text-cyan-300"/><h3 className="mt-4 font-black">{t}</h3></div>)}</div></div></section>
<section className="section"><div className="shell grid gap-10 lg:grid-cols-[.85fr_1.15fr]"><div><SectionHeading eyebrow="¿POR QUÉ ELEGIRNOS?" title={<>Más opciones. Más libertad.<br/><span className="text-[#168db7]">Más conectividad.</span></>} text="Acercamos las mejores alternativas de telefonía móvil, en un mismo lugar."/><Link to="/puntos-de-venta" className="btn-secondary mt-7">Conoce la oportunidad <ArrowRight size={16}/></Link></div><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{[[Building2,'Empresa mexicana','Comprometida con facilitar el acceso a la conectividad móvil.'],[Smartphone,'Diferentes compañías','Opciones para distintos tipos de usuarios.'],[RefreshCw,'Flexibilidad','Nuevas líneas o cambio de compañía.'],[ShieldCheck,'Información para decidir','Asesoría sobre planes, cobertura y beneficios.']].map(([I,t,d])=><InfoCard key={t} icon={I} title={t} text={d}/>)}</div></div></section>
<section className="shell pb-16"><div className="rounded-[28px] bg-[#082a47] p-8 text-white md:flex md:items-center md:justify-between md:p-10"><div><p className="eyebrow text-cyan-300">¿TE GUSTARÍA SER PARTE DE NUESTRA RED?</p><h2 className="mt-2 text-3xl font-black">Conviértete en Punto de Venta</h2><p className="mt-2 text-slate-300">Ofrece a tus clientes más opciones de conectividad.</p></div><Link to="/puntos-de-venta" className="btn-primary mt-6 md:mt-0">Quiero ser Punto de Venta <ArrowRight size={16}/></Link></div></section></div>}
