import { ArrowRight, Store, Users, Wrench, TrendingUp, CheckCircle2, FileText, GraduationCap } from 'lucide-react'
import { Link } from 'react-router-dom'
import VisualHero from '../components/VisualHero'
import InfoCard from '../components/InfoCard'
import SectionHeading from '../components/SectionHeading'
export default function SalesPoints(){const benefits=[[Store,'Amplía tu catálogo','Ofrece nuevas opciones de conectividad a tus clientes.'],[Users,'Más opciones','Permite que tus clientes puedan elegir entre diferentes alternativas.'],[Wrench,'Herramientas y apoyo','Accede a recursos e información para comenzar a operar.'],[TrendingUp,'Nuevas oportunidades','Integra nuevas opciones a tu Punto de Venta.']];return <div className="page"><VisualHero eyebrow="PUNTOS DE VENTA Y SOCIOS COMERCIALES" title="Haz crecer tu negocio con Evolución Telefónica." text="Integra soluciones de conectividad a tu negocio y ofrece a tus clientes diferentes opciones de compañías telefónicas en un solo lugar." image="https://images.unsplash.com/photo-1556742044-3c52d6e88c62?auto=format&fit=crop&w=1800&q=85" primary="Quiero ser Punto de Venta" primaryLink="/contacto" dark/>
<section className="section"><div className="shell"><SectionHeading eyebrow="BENEFICIOS PARA TU NEGOCIO" title="Una oportunidad para ampliar tu oferta comercial."/><div className="mt-10 grid gap-5 md:grid-cols-2 lg:grid-cols-4">{benefits.map(([I,t,d])=><InfoCard key={t} icon={I} title={t} text={d}/>)}</div></div></section>
<section className="bg-[#eaf4f7]"><div className="shell section"><SectionHeading eyebrow="¿CÓMO SER PUNTO DE VENTA?" title="Comienza en cuatro pasos." center/><div className="mt-10 grid gap-5 md:grid-cols-4">{[['1','Regístrate','Déjanos tus datos y cuéntanos sobre tu negocio.'],['2','Conoce la propuesta','Recibe información sobre las opciones disponibles.'],['3','Inicia tu proceso','Conoce requisitos y herramientas necesarias.'],['4','Comienza a vender','Integra las soluciones a tu Punto de Venta.']].map(([n,t,d])=><div key={n} className="soft-card relative"><span className="flex h-10 w-10 items-center justify-center rounded-full bg-[#168db7] font-black text-white">{n}</span><h3 className="mt-5 font-black text-[#17324a]">{t}</h3><p className="mt-2 text-sm leading-6 text-slate-600">{d}</p></div>)}</div></div></section>
<section className="dark-band"><div className="shell grid gap-8 py-12 lg:grid-cols-[1fr_auto]"><div><p className="eyebrow text-cyan-300">¿TIENES DUDAS?</p><h2 className="mt-2 text-3xl font-black text-white">Estamos para ayudarte.</h2><p className="mt-2 text-slate-300">Conoce la propuesta y recibe orientación para comenzar.</p></div><div className="flex items-center"><Link to="/contacto" className="btn-primary">Contáctanos <ArrowRight size={16}/></Link></div></div></section></div>}
